name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set tag
      id: tag
      run: |
        # Use a date-based tag with short SHA (you can customize this)
        TAG="v$(date +%Y%m%d).${{ github.run_number }}"
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "Using tag: $TAG"

    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag git.startechs.xyz/${{ github.repository }}:$TAG \
          --tag git.startechs.xyz/${{ github.repository }}:latest

    - name: Docker login
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
      run: docker login -u $USER -p $PASS git.startechs.xyz

    - name: Push tagged image
      run: |
        docker push git.startechs.xyz/${{ github.repository }}:$TAG
        docker push git.startechs.xyz/${{ github.repository }}:latest
